"""empty message

Revision ID: 0c0e45b176e5
Revises: 
Create Date: 2019-08-12 16:55:10.585788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0e45b176e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emoji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emoji')
    )
    op.create_table('fb_messenger_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_mid', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_mid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fb_messenger_message')
    op.drop_table('emoji')
    # ### end Alembic commands ###
